name: Docker build and push
description: Build and push docker image to container registry

inputs:
  registry:
    description: "Registry name"
    required: true
    default: "eu.gcr.io"
  username:
    description: "Registry username"
    required: true
    default: "_json_key"
  password:
    description: "Registry password"
    required: true
  tags:
    description: "List of tags"
    required: true
  context:
    description: "Folder containing Dockerfile. Context parameter for docker/build-push-action action"
    required: true
    default: "."
  target:
    description: "Sets the target stage to build"
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Login to google container repo
      uses: docker/login-action@v1 
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Tag and publish
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
        target: ${{ inputs.target }}
