name: Upload docs
description: Upload documentation

inputs:
  docs_bucket_sa:
    description: "Documentation bucket service account"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup gcloud credentials
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: prod-econo-cm
        service_account_key: ${{ inputs.docs_bucket_sa }}
        export_default_credentials: true

    - name: Upload docs
      shell: bash
      run: |
        mkdir -p ./_docs-prepare

        echo "Copying README.md file from the root directory"
        find -maxdepth 1 -iname readme.md -exec cp {} ./_docs-prepare \;

        if [[ -d ./docs ]]
        then
            echo "'docs' directory exists, prepearing for upload"
            cp -R ./docs ./_docs-prepare/
        fi

        echo "Listing docs prepared directory structure"
        ls -alR ./_docs-prepare

        echo "Removing existing docs for ${{ github.event.repository.name }}"
        gsutil -m rm -r gs://prod-econo-cm_docs/${{ github.event.repository.name }} 2>&1 || true

        echo "Uploading docs to Google Cloud Storage for ${{ github.event.repository.name }}"
        gsutil -m cp -r ./_docs-prepare gs://prod-econo-cm_docs/${{ github.event.repository.name }}
